//
//  WebPagePieceBase.cs
//
//  Author:
//       Willem Van Onsem <Willem.VanOnsem@cs.kuleuven.be>
//
//  Copyright (c) 2014 Willem Van Onsem
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
using IdpGie.Engines;
using System.Linq;
using System.Web.UI;
using System.Xml.Serialization;
using System.Collections.Generic;
using HtmlAgilityPack;
using IdpGie.Shapes.Web;
using IdpGie.Abstract;

namespace IdpGie.Shapes.Pages {
	/// <summary>
	/// A basic implementation of the <see cref="IWebPagePiece"/> interface. A piece of a webpage
	/// that is static in case it is default HTML or dynamic in case it is generated by a <see cref="IWebShape"/>.
	/// </summary>
	public abstract class WebPagePieceBase : IWebPagePiece {

		#region IId implementation
		/// <summary>
		/// Gets the id of this instance.
		/// </summary>
		/// <value>The id of this instance, a unique number.</value>
		[XmlIgnore]
		public virtual ulong Id {
			get;
			private set;
		}
		#endregion
		#region IWebPagePiece implementation
		/// <summary>
		/// Gets the pieces that compose the <see cref="IWebPage"/>.
		/// </summary>
		/// <value>
		/// The pieces that compose the <see cref="IWebPage"/>.
		/// </value>
		public virtual IList<IWebPagePiece> Pieces {
			get {
				return new IWebPagePiece[0x00];
			}
		}
		#endregion
		/// <summary>
		/// Initializes a new instance of the <see cref="IdpGie.Shapes.Pages.WebPagePieceBase"/> class.
		/// </summary>
		protected WebPagePieceBase () {
			this.Id = IdDispatcher.getId ();
		}
		#region IWebPagePiece implementation
		/// <summary>
		/// Loading the page from the given server folder.
		/// </summary>
		/// <param name='serverFolder'>
		/// The root of the folder of the web server.
		/// </param>
		public virtual void Load (string serverFolder) {
		}

		/// <summary>
		///  Render the webpage onto the give specified engine. 
		/// </summary>
		/// <param name='serverFolder'>
		///  The root of the folder of the web server. 
		/// </param>
		/// <param name='engine'>
		///  The given specified engine. 
		/// </param>
		/// <param name='writer'>
		///  The html writer to write content to. 
		/// </param>
		public abstract void Render (string serverFolder, HttpEngine engine, Html32TextWriter writer);

		/// <summary>
		/// Registers the query pages that can be activated in the specified <see cref="INavbar"/>.
		/// </summary>
		/// <param name="navbar">The <see cref="INavbar"/> to register <see cref="IQueryWebPage"/> instance.</param>
		public virtual void RegisterQueryPages (INavbar navbar) {
			if (this.Pieces != null) {
				foreach (IWebPagePiece piece in this.Pieces) {
					piece.RegisterQueryPages (navbar);
				}
			}
		}
		#endregion
		/// <summary>
		/// Translates the given node into a <see cref="IWebPagePiece"/>.
		/// </summary>
		/// <returns>
		/// An <see cref="IWebPagePiece"/> that corresponds to the given node.
		/// </returns>
		/// <param name='node'>
		/// The given <see cref="HtmlNode"/> to translate.
		/// </param>
		public static IWebPagePiece Translate (HtmlNode node) {
			switch (node.NodeType) {
				case HtmlNodeType.Element:
					if (WebShapeBase.ContainsTag (node.Name)) {
						return WebShapeBase.DecodeWebShape (node).GetPagePiece ();
					} else {
						return new HtmlElementPagePiece (node);
					}
				case HtmlNodeType.Text:
					return new HtmlTextWebPagePiece (node.InnerHtml);
				default :
					return DefaultWebPagePiece.SingleInstance;
			}
		}

		/// <summary>
		/// Translates the given node into a <see cref="IWebPagePiece"/>.
		/// </summary>
		/// <returns>
		/// An <see cref="System.Array"/> of <see cref="IWebPagePiece"/> instances that
		/// corresponds to the children of the given node.
		/// </returns>
		/// <param name='parent'>
		/// The given <see cref="HtmlNode"/> to expand.
		/// </param>
		public static IList<IWebPagePiece> Expand (HtmlNode parent) {
			return parent.ChildNodes.Select (Translate).ToArray ();
		}
	}
}