
// This file has been generated by the GUI designer. Do not modify.
namespace IdpGie
{
	public partial class TopWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action ControlsAction;
		private global::Gtk.Action PlayAction;
		private global::Gtk.Action PauseAction;
		private global::Gtk.Action RewindAction;
		private global::Gtk.Action ForwardAction;
		private global::Gtk.Action PreviousChapterAction;
		private global::Gtk.Action NextChapterAction;
		private global::Gtk.VBox vbox1;
		private global::Gtk.MenuBar menubar1;
		private global::IdpGie.BlueprintMediabar blueprintmediabar1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget IdpGie.TopWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.ControlsAction = new global::Gtk.Action ("ControlsAction", global::Mono.Unix.Catalog.GetString ("Controls"), null, null);
			this.ControlsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Controls");
			w1.Add (this.ControlsAction, null);
			this.PlayAction = new global::Gtk.Action ("PlayAction", global::Mono.Unix.Catalog.GetString ("Play"), null, "play");
			this.PlayAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Play");
			w1.Add (this.PlayAction, null);
			this.PauseAction = new global::Gtk.Action ("PauseAction", global::Mono.Unix.Catalog.GetString ("Pause"), null, "pause");
			this.PauseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Pause");
			w1.Add (this.PauseAction, null);
			this.RewindAction = new global::Gtk.Action ("RewindAction", global::Mono.Unix.Catalog.GetString ("Rewind"), null, "rewind");
			this.RewindAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Rewind");
			w1.Add (this.RewindAction, null);
			this.ForwardAction = new global::Gtk.Action ("ForwardAction", global::Mono.Unix.Catalog.GetString ("Forward"), null, "forward");
			this.ForwardAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Forward");
			w1.Add (this.ForwardAction, null);
			this.PreviousChapterAction = new global::Gtk.Action ("PreviousChapterAction", global::Mono.Unix.Catalog.GetString ("Previous Chapter"), null, "previous");
			this.PreviousChapterAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Previous Chapter");
			w1.Add (this.PreviousChapterAction, null);
			this.NextChapterAction = new global::Gtk.Action ("NextChapterAction", global::Mono.Unix.Catalog.GetString ("Next Chapter"), null, "next");
			this.NextChapterAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Next Chapter");
			w1.Add (this.NextChapterAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "IdpGie.TopWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("TopWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child IdpGie.TopWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='ControlsAction' action='ControlsAction'><menuitem name='PlayAction' action='PlayAction'/><menuitem name='PauseAction' action='PauseAction'/><menuitem name='RewindAction' action='RewindAction'/><menuitem name='ForwardAction' action='ForwardAction'/><menuitem name='PreviousChapterAction' action='PreviousChapterAction'/><menuitem name='NextChapterAction' action='NextChapterAction'/></menu></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.blueprintmediabar1 = new global::IdpGie.BlueprintMediabar ();
			this.blueprintmediabar1.Name = "blueprintmediabar1";
			this.blueprintmediabar1.Min = 0;
			this.blueprintmediabar1.Max = 0;
			this.blueprintmediabar1.Current = 0;
			this.blueprintmediabar1.Speed = 0;
			this.vbox1.Add (this.blueprintmediabar1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.blueprintmediabar1]));
			w3.Position = 2;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
