
// This file has been generated by the GUI designer. Do not modify.
namespace IdpGie
{
	public partial class TopWindow
	{
		private global::Gtk.VBox vbox1;
		private global::IdpGie.BlueprintMediabar blueprintmediabar1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget IdpGie.TopWindow
			this.Name = "IdpGie.TopWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("TopWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child IdpGie.TopWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.blueprintmediabar1 = new global::IdpGie.BlueprintMediabar ();
			this.blueprintmediabar1.Name = "blueprintmediabar1";
			this.blueprintmediabar1.Min = 0;
			this.blueprintmediabar1.Max = 0;
			this.blueprintmediabar1.Current = 0;
			this.blueprintmediabar1.Speed = 0;
			this.vbox1.Add (this.blueprintmediabar1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.blueprintmediabar1]));
			w1.Position = 2;
			w1.Expand = false;
			w1.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
