//
//  IWebShape.cs
//
//  Author:
//       Willem Van Onsem <Willem.VanOnsem@cs.kuleuven.be>
//
//  Copyright (c) 2014 Willem Van Onsem
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

using IdpGie.Shapes.Pages;
using IdpGie.Abstract;
using System.Collections.Generic;

namespace IdpGie.Shapes.Web {
	/// <summary>
	/// An interface describing an interactive object that is part of the webpage.
	/// </summary>
	public interface IWebShape : IId {

		/// <summary>
		/// Gets a page piece that performs the bridge between the webpage and the <see cref="IQueryWebPage"/> instances
		/// generated by this <see cref="IWebShape"/>.
		/// </summary>
		/// <returns>A page piece to inject in the generated page to bind with the generated <see cref="IQueryWebPage"/>.</returns>
		IWebPagePiece GetPagePiece ();

		/// <summary>
		/// Gets the <see cref="IQueryWebPage"/> instances associated with this <see cref="IWebPage"/>.
		/// </summary>
		/// <returns>The <see cref="IQueryWebPage"/> instances associated with this <see cref="IWebPage"/>.</returns>
		IEnumerable<IQueryWebPage> GetQueryPages ();
	}
}