//
//  WebShape.cs
//
//  Author:
//       Willem Van Onsem <Willem.VanOnsem@cs.kuleuven.be>
//
//  Copyright (c) 2014 Willem Van Onsem
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
using IdpGie.Shapes.Pages;
using System.Reflection;
using System;

namespace IdpGie.Shapes.Web {
	/// <summary>
	/// A basic abstract implementation of a web shape.
	/// </summary>
	public abstract class WebShapeBase : IWebShape {

		/// <summary>
		/// Initializes a new instance of the <see cref="WebShape"/> class.
		/// </summary>
		protected WebShapeBase () {
		}
		#region IWebShape implementation
		/// <summary>
		/// Translates the given <see cref="IWebShape"/> into a relevant <see cref="IQueryWebPage"/> instance.
		/// </summary>
		/// <returns>
		/// An <see cref="IQueryWebPage"/> instances that can produce dynamic content.
		/// </returns>
		public abstract IQueryWebPage GetQueryPage ();

		/// <summary>
		/// Gets a page piece that performs the bridge between the webpage and the <see cref="IQueryWebPage"/>\
		/// generated by the <see cref="GetQueryPage()"/> method.
		/// </summary>
		/// <returns>A page piece to inject in the generated page to bind with the generated <see cref="IQueryWebPage"/>.</returns>
		public abstract IWebPagePiece GetPagePiece ();
		#endregion
		#region Static methods
		/// <summary>
		/// Analyzes the given assembly and adds stores the founded webshape tags. They are then used to translate
		/// specific inline tags into the corresponding webshapes.
		/// </summary>
		/// <param name="assembly">The assembly to analyze.</param>
		public static void AnalyzeAssembly (Assembly assembly) {
			foreach (Type t in assembly.GetTypes ()) {
				analyzeType (t);
			}
		}

		/// <summary>
		/// Analyzes the type.
		/// </summary>
		/// <param name="type">Type.</param>
		private static void analyzeType (Type type) {

		}
		#endregion
	}
}

